'use client';

import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { downloadAsImage } from '@/lib/downloadImage';

export default function AnnouncementAgent() {
  const [mounted, setMounted] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [language, setLanguage] = useState<'en-US' | 'hi-IN' | 'ur-PK'>('en-US');
  const [activeAgent, setActiveAgent] = useState<string>('');
  const [formData, setFormData] = useState({
    event: '',
    date: '',
    topic: '',
    result: ''
  });
  const [status, setStatus] = useState('');
  const cardRef = useRef<HTMLDivElement>(null);

  useEffect(() => { setMounted(true); }, []);

  const getLangLabel = () => {
    switch(language) {
      case 'en-US': return '🇬🇧 EN';
      case 'hi-IN': return '🇮🇳 HI';
      case 'ur-PK': return '🇵🇰 UR';
    }
  };

  const cycleLang = () => {
    const langs: Array<'en-US' | 'hi-IN' | 'ur-PK'> = ['en-US', 'hi-IN', 'ur-PK'];
    const idx = langs.indexOf(language);
    setLanguage(langs[(idx + 1) % 3]);
  };

  // Voice-to-Text
  const startListening = (field: 'event' | 'topic') => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert("Browser doesn't support Voice. Use Chrome or Edge.");
      return;
    }

    const recognition = new SpeechRecognition();
    recognition.lang = language;
    recognition.onstart = () => setIsRecording(true);
    recognition.onresult = (event: any) => {
      const transcript = event.results[0][0].transcript;
      setFormData(prev => ({ ...prev, [field]: transcript }));
      setIsRecording(false);
    };
    recognition.onerror = () => setIsRecording(false);
    recognition.onend = () => setIsRecording(false);
    recognition.start();
  };

  // Multi-Agent AI Generation
  const generateAnnouncement = async () => {
    if (!formData.event) {
      setStatus('⚠️ Please enter an event name');
      return;
    }
    setIsGenerating(true);
    setStatus('🤖 Detecting agent...');
    setActiveAgent('');

    try {
      const response = await fetch('/api/generate-announcement', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          eventName: formData.event,
          dateTime: formData.date,
          topic: formData.topic,
        }),
      });

      const data = await response.json();
      if (data.success && data.announcement) {
        setFormData(prev => ({ ...prev, result: data.announcement }));
        setActiveAgent(data.agentName || data.agent || '');
        setStatus(`✅ Generated by ${data.agentName || 'AI Agent'}`);
      } else {
        throw new Error('Failed');
      }
    } catch (error) {
      // Professional Template Fallback
      const fallback = `*_Assalam-o-Alaikum!_* ✨\n\n*_Dear Students,_*\n\n📢 *ANNOUNCEMENT* 📢\n━━━━━━━━━━━━━━━━━━━━\n\n📌 *${formData.event.toUpperCase()}*\n\n📅 *Date:* ${formData.date || 'To be announced'}\n\n📝 *Details:*\n${formData.topic || 'Important session for all students.'}\n\n━━━━━━━━━━━━━━━━━━━━\n\n✅ Don't miss this opportunity!\n📍 Visit your nearest SMIT campus\n\n🏛️ *Saylani Mass IT Training*\n🌐 saylaniwelfare.com/smit\n📞 Helpline: 0800-786-786\n\n*Best regards,*\n*SMIT MANAGEMENT*\n\n#SMIT #SaylaniWelfare #FreeITEducation`;
      setFormData(prev => ({ ...prev, result: fallback }));
      setActiveAgent('GENERIC AGENT');
      setStatus('✅ Generated with Template');
    } finally {
      setIsGenerating(false);
    }
  };

  // Text-to-Speech
  const speakAnnouncement = () => {
    if (!formData.result) return;

    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    const mainMessage = `Assalam-o-Alaikum! Attention SMIT Students. Regarding ${formData.event}. ${formData.topic || ''}. Please check the announcement for timings and venue. Best regards, SMIT Management.`;

    const utterance = new SpeechSynthesisUtterance(mainMessage);
    utterance.rate = 0.9;
    utterance.lang = language;

    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend = () => setIsSpeaking(false);
    window.speechSynthesis.speak(utterance);
  };

  const handleDownload = async () => {
    if (cardRef.current) {
      await downloadAsImage(cardRef.current, `smit-announcement-${Date.now()}.png`);
      setStatus('📥 Image downloaded!');
    }
  };

  const shareWhatsApp = () => {
    if (!formData.result) return;
    const encoded = encodeURIComponent(formData.result);
    window.open(`https://api.whatsapp.com/send?text=${encoded}`, '_blank');
  };

  const copyText = async () => {
    if (!formData.result) return;
    await navigator.clipboard.writeText(formData.result);
    setStatus('📋 Copied to clipboard!');
  };

  if (!mounted) return null;

  return (
    <div className="min-h-screen bg-[#f8fafc]">
      {/* Header */}
      <header className="bg-gradient-to-r from-[#0066cc] to-[#8cc63f] text-white py-4 px-6 shadow-lg">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 hover:opacity-90 transition">
            <div className="bg-white p-1 rounded-full">
              <Image src="/smit-logo.svg" alt="SMIT" width={40} height={40} />
            </div>
            <div>
              <h1 className="text-xl font-bold">SMIT Multi-Agent</h1>
              <p className="text-xs opacity-90">Announcement Generator</p>
            </div>
          </Link>
          <nav className="flex gap-4">
            <Link href="/" className="hover:opacity-80 transition">Home</Link>
            <Link href="/chat" className="hover:opacity-80 transition">FAQ Chat</Link>
          </nav>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-8">
        {/* Title */}
        <div className="text-center mb-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-2">
            🤖 Multi-Agent Announcement System
          </h2>
          <p className="text-gray-600 text-sm">
            AI automatically selects the right agent: 💰 Finance | 🎓 Admissions | 🔥 Event | 📢 Generic
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* LEFT: INPUT FORM */}
          <div className="bg-white rounded-2xl p-6 shadow-md border border-gray-100">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-bold text-gray-800">✏️ Announcement Details</h3>
              <button
                onClick={cycleLang}
                className="text-xs bg-gray-100 px-3 py-2 rounded-lg hover:bg-gray-200 transition font-medium"
              >
                {getLangLabel()} ↻
              </button>
            </div>

            <div className="space-y-4">
              {/* Event Name */}
              <div>
                <label className="text-sm font-semibold text-gray-700 block mb-1">
                  Event Name *
                </label>
                <div className="flex gap-2">
                  <input
                    className="flex-1 p-3 border-2 border-gray-200 rounded-xl text-gray-900 bg-white focus:border-[#0066cc] outline-none transition"
                    style={{ color: '#1a202c', WebkitTextFillColor: '#1a202c' }}
                    value={formData.event}
                    onChange={(e) => setFormData({...formData, event: e.target.value})}
                    placeholder="e.g. Fee Submission Deadline"
                  />
                  <button
                    onClick={() => startListening('event')}
                    className={`p-3 rounded-xl transition-all shadow ${isRecording ? 'bg-red-500 animate-pulse scale-110' : 'bg-gradient-to-r from-[#0066cc] to-[#8cc63f] hover:scale-105'} text-white`}
                  >
                    🎤
                  </button>
                </div>
              </div>

              {/* Date/Time with Calendar Picker */}
              <div>
                <label className="text-sm font-semibold text-gray-700 block mb-1">
                  📅 Date & Time
                </label>
                <input
                  type="datetime-local"
                  className="w-full p-3 border-2 border-gray-200 rounded-xl text-gray-900 bg-white focus:border-[#0066cc] outline-none transition cursor-pointer"
                  style={{ color: '#1a202c', WebkitTextFillColor: '#1a202c' }}
                  value={formData.date}
                  onChange={(e) => setFormData({...formData, date: e.target.value})}
                />
              </div>

              {/* Topic/Details */}
              <div>
                <label className="text-sm font-semibold text-gray-700 block mb-1">
                  Topic / Details
                </label>
                <div className="flex gap-2">
                  <textarea
                    className="flex-1 p-3 border-2 border-gray-200 rounded-xl text-gray-900 bg-white focus:border-[#0066cc] outline-none resize-none transition"
                    style={{ color: '#1a202c', WebkitTextFillColor: '#1a202c' }}
                    rows={3}
                    value={formData.topic}
                    onChange={(e) => setFormData({...formData, topic: e.target.value})}
                    placeholder="e.g. All students must pay fees before deadline..."
                  />
                  <button
                    onClick={() => startListening('topic')}
                    className={`p-3 rounded-xl self-start transition-all shadow ${isRecording ? 'bg-red-500 animate-pulse' : 'bg-gradient-to-r from-[#0066cc] to-[#8cc63f] hover:scale-105'} text-white`}
                  >
                    🎤
                  </button>
                </div>
              </div>

              {/* Agent Keywords Hint */}
              <div className="bg-gray-50 rounded-xl p-4 text-xs text-gray-600">
                <p className="font-semibold text-gray-700 mb-2">💡 Agent Detection Keywords:</p>
                <div className="grid grid-cols-2 gap-2">
                  <span>💰 <b>Finance:</b> fee, payment, dues</span>
                  <span>🎓 <b>Admissions:</b> course, apply, batch</span>
                  <span>🔥 <b>Event:</b> hackathon, workshop</span>
                  <span>📢 <b>Generic:</b> everything else</span>
                </div>
              </div>

              {/* Generate Button */}
              <button
                onClick={generateAnnouncement}
                disabled={isGenerating}
                className="w-full bg-gradient-to-r from-[#0066cc] to-[#8cc63f] text-white p-4 rounded-xl font-bold shadow-lg hover:opacity-90 transition disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {isGenerating ? (
                  <>⏳ Generating...</>
                ) : (
                  <>✨ Generate with AI</>
                )}
              </button>

              {/* Status & Active Agent */}
              {status && (
                <p className="text-center text-sm text-[#0066cc] font-semibold">{status}</p>
              )}
              {activeAgent && (
                <p className="text-center text-xs bg-gradient-to-r from-[#0066cc] to-[#8cc63f] text-white py-2 px-4 rounded-full inline-block mx-auto">
                  🤖 {activeAgent}
                </p>
              )}
            </div>
          </div>

          {/* RIGHT: PREVIEW & ACTIONS */}
          <div className="space-y-6">
            <h3 className="text-lg font-bold text-gray-800">👁️ Preview</h3>

            {/* Preview Card */}
            <div
              ref={cardRef}
              className="bg-white rounded-2xl shadow-xl border-4 border-[#8cc63f] overflow-hidden"
            >
              {/* Card Header */}
              <div className="bg-gradient-to-r from-[#0066cc] to-[#8cc63f] text-white py-4 px-5">
                <div className="flex items-center gap-3">
                  <Image src="/smit-logo.svg" alt="SMIT" width={45} height={45} className="bg-white rounded-full p-1" />
                  <div>
                    <p className="font-bold">SMIT</p>
                    <p className="text-xs opacity-90">Saylani Mass IT Training</p>
                  </div>
                </div>
              </div>

              {/* Card Content */}
              <div className="p-6">
                {formData.result ? (
                  <pre className="whitespace-pre-wrap text-gray-900 font-sans text-sm leading-relaxed">
                    {formData.result}
                  </pre>
                ) : (
                  <div className="text-center py-16 text-gray-400">
                    <span className="text-4xl block mb-3">🤖</span>
                    <p className="font-medium">AI-generated announcement will appear here</p>
                    <p className="text-sm mt-1">Fill the form and click Generate</p>
                  </div>
                )}
              </div>
            </div>

            {/* Action Buttons */}
            {formData.result && (
              <div className="space-y-3">
                {/* Play Voice Button */}
                <button
                  onClick={speakAnnouncement}
                  className={`w-full p-4 rounded-xl font-bold flex items-center justify-center gap-2 transition shadow-lg ${
                    isSpeaking
                      ? 'bg-red-500 text-white'
                      : 'bg-gradient-to-r from-[#0066cc] to-[#8cc63f] text-white hover:opacity-90'
                  }`}
                >
                  {isSpeaking ? '⏹️ Stop Voice' : '🔊 Play Voice'}
                </button>

                {/* Share Buttons Row */}
                <div className="flex gap-2">
                  <button
                    onClick={handleDownload}
                    className="flex-1 p-3 bg-[#0066cc] text-white rounded-xl font-bold hover:opacity-90 transition flex items-center justify-center gap-2"
                  >
                    📥 Download
                  </button>
                  <button
                    onClick={shareWhatsApp}
                    className="flex-1 p-3 bg-[#25D366] text-white rounded-xl font-bold hover:opacity-90 transition flex items-center justify-center gap-2"
                  >
                    📱 WhatsApp
                  </button>
                  <button
                    onClick={copyText}
                    className="p-3 border-2 border-gray-200 rounded-xl bg-white hover:border-[#0066cc] transition"
                    title="Copy to clipboard"
                  >
                    📋
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gradient-to-r from-[#0066cc] to-[#8cc63f] text-white py-6 mt-16">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <p className="text-sm opacity-90">
            SMIT - Saylani Mass IT Training | Building Future Tech Leaders
          </p>
        </div>
      </footer>
    </div>
  );
}
